### ISSUE TITLE
Support RINEX v3.04

### ISSUE THREAD

**Issue by i-zhivetiev** [gnss-lab/tec-suite#16]

**Comment by AmadiBrians** [comment]
Please how can I fix this error:

There are some errors, check out the log-file: tec/tecs.log.

**Comment by i-zhivetiev** [comment]
Hello, 

It’s just a way to tell that the program has encountered some errors while reading RINEX files. For the most part, these are errors in the concrete RINEX files. You can check out the tecs.log file to see the matter, but you cannot fix this. Just ignore.
